name: Pull Request Update

on:
  pull_request:
    types: [closed]

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: make .env file
        run: echo "GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}" > .env
      - name: Install dependencies
        run: npm install
        working-directory: src
      - name: install poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "PATH=$HOME/.local/bin:$PATH" >> $GITHUB_ENV
      - name: Install dependencies
        run: poetry install --no-root
        working-directory: src
      - name: run check for changed files
        run: poetry run python ymls_to_ldes_ttl.py
        working-directory: src
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./ldes
      - name: Commit and push changes to main branch
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'